# Issue sentences – corpo email (versione estesa)
issues = {
    "Legale": [
        "È necessaria la revisione di una clausola contrattuale.",
        "Dobbiamo avviare una procedura legale per inadempienza.",
        "Il contratto ricevuto non è conforme ai requisiti normativi.",
        "Serve un parere sulla validità di una clausola di non concorrenza.",
        "È richiesto un aggiornamento in materia di GDPR per il nuovo servizio.",
        "È stato notificato un atto di citazione per violazione di marchio.",
        "Occorre preparare una lettera di diffida per mancato pagamento.",
        "Va esaminato un accordo di riservatezza prima della firma.",
        "Si prospetta un arbitrato internazionale con un fornitore estero.",
        "È in scadenza il termine per impugnare una delibera assembleare.",
        "Dobbiamo redigere un contratto di licenza software.",
        "È arrivata una richiesta di mediazione obbligatoria.",
        "Occorre valutare la risoluzione anticipata di un contratto di appalto.",
        "È stata segnalata una possibile violazione di proprietà intellettuale.",
        "Serve assistenza per la registrazione di un marchio.",
        "Va predisposto un verbale di conciliazione sindacale.",
        "È necessario verificare la clausola di manleva in un contratto quadro.",
        "Dobbiamo rispondere a una lettera di messa in mora.",
        "Occorre aggiornare i contratti standard alla normativa antitrust.",
        "Serve assistenza per depositare un brevetto.",
        "Una diffida è stata inviata per un utilizzo improprio del marchio.",
        "Un cliente ha chiesto chiarimenti su responsabilità contrattuale.",
        "Un parere è richiesto su una clausola di esclusiva commerciale.",
        "Contratto internazionale in fase di traduzione giuridica.",
        "Notifica ricevuta per presunta concorrenza sleale.",
        "È richiesta verifica su clausola di penale contrattuale.",
        "Serve supporto per predisporre termini di risoluzione.",
        "Una clausola di forza maggiore va adeguata alla normativa vigente.",
        "Il cliente chiede accesso ai documenti legali del contratto.",
        "È necessario rivedere una clausola del contratto che desta dubbi.",
        "Occorre avviare un'azione legale per violazione degli obblighi contrattuali.",
        "Il contratto in nostro possesso non rispetta i criteri previsti dalla normativa vigente.",
        "Chiediamo un parere legale sulla validità di una clausola di esclusività.",
        "Serve un aggiornamento normativo riguardante il GDPR per l’attivazione del nuovo servizio.",
        "Abbiamo ricevuto un atto giudiziario per sospetta violazione di marchio registrato.",
        "È urgente redigere una lettera formale di diffida per insolvenza da parte del cliente.",
        "Dobbiamo analizzare un NDA prima della sottoscrizione ufficiale.",
        "Si sta valutando una procedura arbitrale internazionale con un partner estero.",
        "Scade a breve il termine utile per presentare ricorso contro una delibera assembleare.",
        "È necessario predisporre un contratto per la concessione d’uso software.",
        "Un soggetto terzo ha richiesto formalmente l’avvio della mediazione obbligatoria.",
        "Stiamo considerando la cessazione anticipata di un contratto d’appalto per giusta causa.",
        "È emersa una possibile infrazione nel campo della proprietà intellettuale.",
        "Richiesta assistenza per registrare un marchio presso l’Ufficio Brevetti.",
        "Dobbiamo redigere un verbale per una conciliazione sindacale programmata.",
        "Va effettuata un’analisi della clausola di manleva inserita nel contratto quadro.",
        "È necessario rispondere a una comunicazione di costituzione in mora.",
        "I contratti in uso vanno aggiornati per allinearli alla normativa antitrust.",
        "È richiesta consulenza per procedere al deposito di un nuovo brevetto.",
        "È stata inviata una diffida per l’uso scorretto di un marchio registrato.",
        "Un cliente ha sollevato dubbi sulle responsabilità definite nel contratto.",
        "È stato richiesto un parere giuridico su una clausola di esclusività.",
        "Un contratto internazionale è attualmente in fase di revisione legale e traduzione.",
        "Abbiamo ricevuto una notifica formale per possibile concorrenza sleale.",
        "Si richiede verifica di una clausola penale inclusa nel contratto.",
        "Occorre supporto per strutturare correttamente i termini di scioglimento contrattuale.",
        "La clausola di forza maggiore necessita un aggiornamento per riflettere la normativa attuale.",
        "Il cliente ha chiesto di consultare i documenti legali allegati al contratto firmato." 
    ],

    "Contabilità": [
        "Sono presenti incongruenze nel bilancio mensile.",
        "Manca la documentazione di alcune spese.",
        "I totali non coincidono con l’estratto conto bancario.",
        "Il registro IVA presenta differenze rispetto alla prima nota.",
        "Risultano fatture registrate due volte sul gestionale.",
        "Occorre rettificare ammortamenti calcolati erroneamente.",
        "Il fondo cassa risulta negativo rispetto al libro giornale.",
        "Serve la riconciliazione dei movimenti PayPal.",
        "È mancante la prima nota di gennaio nel sistema.",
        "Alcuni costi sono stati imputati al centro di costo sbagliato.",
        "I ratei attivi non sono stati rilevati a fine trimestre.",
        "Il saldo clienti non è allineato con la reportistica commerciale.",
        "Non risultano registrati gli interessi bancari trimestrali.",
        "La quadratura del libro cespiti non torna con il bilancio.",
        "Sono stati registrati incassi su conti errati.",
        "Le scritture di assestamento non sono state completate.",
        "Il prospetto liquidazione IVA mostra un saldo anomalo.",
        "I pagamenti stipendi non corrispondono al payroll.",
        "Una nota di debito è stata contabilizzata come nota di credito.",
        "Serve il ricalcolo delle ritenute d’acconto su compensi professionali.",
        "Sono emerse discrepanze nel bilancio relativo al mese corrente.",
        "La documentazione di supporto per alcune spese risulta assente.",
        "I saldi non corrispondono ai movimenti indicati nell’estratto conto bancario.",
        "Sono state rilevate anomalie tra il registro IVA e la prima nota contabile.",
        "Alcune fatture risultano duplicate nel sistema gestionale.",
        "Bisogna correggere errori nel calcolo degli ammortamenti.",
        "Il fondo cassa presenta un saldo inferiore rispetto a quanto registrato sul giornale contabile.",
        "È richiesta una verifica e riconciliazione dei movimenti effettuati tramite PayPal.",
        "Nel gestionale manca la registrazione della prima nota di gennaio.",
        "Alcune spese sono state attribuite a centri di costo non corretti.",
        "I ratei attivi non sono stati contabilizzati alla chiusura trimestrale.",
        "Il saldo clienti non coincide con quanto riportato nei report commerciali.",
        "Gli interessi bancari del trimestre non risultano ancora contabilizzati.",
        "La quadratura del libro cespiti mostra scostamenti rispetto al bilancio ufficiale.",
        "Incassi sono stati erroneamente associati a conti bancari differenti.",
        "Le operazioni di assestamento di fine periodo risultano incomplete.",
        "Il prospetto relativo all’IVA presenta un disavanzo non giustificato.",
        "Ci sono differenze tra i pagamenti degli stipendi e quanto registrato in payroll.",
        "Una nota di debito è stata inserita per errore come nota di credito.",
        "È necessario procedere al nuovo calcolo delle ritenute d’acconto per i compensi professionali."
    ],

    "Fatturazione": [
    "Non è stata emessa la fattura relativa all’ordine 2345.",
    "La nota di credito risulta non corretta.",
    "Abbiamo ricevuto una fattura duplicata.",
    "Il numero di fattura non segue la sequenza progressiva.",
    "L’importo IVA è stato calcolato con aliquota errata.",
    "L’intestazione fattura riporta un indirizzo obsoleto.",
    "Il pagamento risulta registrato ma la fattura è ancora aperta.",
    "Serve l’emissione di fattura proforma per anticipo cliente.",
    "È necessario annullare una fattura con storno totale.",
    "Una fattura elettronica è stata scartata dal SDI.",
    "Il CIG/CUP indicato non corrisponde all’ordine pubblico.",
    "È stata richiesta la fatturazione in valuta estera.",
    "Occorre riemettere una fattura con split payment.",
    "Una fattura è stata emessa senza riferimento al PO.",
    "Manca l’allegato PDF in fattura elettronica.",
    "Il codice destinatario è errato nel tracciato XML.",
    "La scadenza di pagamento non rispetta gli accordi contrattuali.",
    "Il cliente chiede l’invio di una fattura cumulativa mensile.",
    "È richiesto un abbuono per arrotondamento su fattura.",
    "La fattura riporta un IBAN non più valido.",
    "La numerazione delle fatture presenta un salto non giustificato.",
    "Una fattura è stata emessa in anticipo rispetto alla consegna.",
    "Il campo 'causale' è mancante nel tracciato XML.",
    "Una fattura è stata inviata con codice SDI errato.",
    "Un cliente ha ricevuto una fattura intestata a un'altra azienda.",
    "L'importo totale non include le spese di spedizione.",
    "Una nota di credito è stata associata all’ordine sbagliato.",
    "Il file XML presenta errori di formattazione.",
    "Una fattura è stata inviata due volte nello stesso giorno.",
    "L’ente pubblico richiede una modifica al codice ufficio.",
    "Non risulta ancora emessa la fattura relativa all’ordine n. 2345.",
    "La nota di credito presenta dati errati e necessita revisione.",
    "Abbiamo ricevuto per errore una fattura già registrata in precedenza.",
    "La numerazione della fattura non rispetta la progressione logica prevista.",
    "L’IVA è stata applicata con una percentuale sbagliata nel documento.",
    "L’intestazione della fattura mostra un indirizzo non più valido.",
    "Il pagamento risulta contabilizzato, ma la relativa fattura risulta ancora aperta.",
    "È richiesta l’emissione urgente di una fattura proforma per anticipo cliente.",
    "Va proceduto all’annullamento completo della fattura tramite storno totale.",
    "Il sistema SDI ha respinto una delle fatture elettroniche inviate.",
    "Il codice CIG o CUP indicato non è in linea con i dati dell’ordine pubblico.",
    "È stata richiesta la generazione della fattura in una valuta diversa dall’euro.",
    "La fattura va riemessa adottando il regime dello split payment.",
    "Un documento è stato emesso senza alcun riferimento al numero di ordine d'acquisto.",
    "Manca l’allegato in formato PDF nella fattura inviata tramite canale elettronico.",
    "Il codice identificativo destinatario nel file XML risulta errato.",
    "La data di scadenza del pagamento non è conforme agli accordi contrattuali.",
    "Il cliente ha chiesto una sola fattura riepilogativa per tutte le operazioni del mese.",
    "È stato richiesto un abbuono a causa di un arrotondamento non corretto nella fattura.",
    "Il numero IBAN indicato nella fattura non è più utilizzabile.",
    "Ci sono anomalie nella sequenza delle numerazioni delle fatture emesse.",
    "Una fattura è stata emessa in data antecedente alla consegna effettiva della merce.",
    "Nel tracciato XML manca il campo relativo alla causale del pagamento.",
    "Il file trasmesso contiene un codice SDI errato, quindi la fattura non è andata a buon fine.",
    "Un cliente ha ricevuto una fattura intestata a un soggetto sbagliato.",
    "L’importo totale della fattura non comprende i costi di spedizione previsti.",
    "È stata emessa una nota di credito per un ordine diverso da quello corretto.",
    "Il file XML inviato contiene errori di struttura o formattazione.",
    "Una stessa fattura è stata trasmessa due volte nella medesima giornata.",
    "L’ente pubblico ha richiesto una correzione del codice ufficio riportato nel file."
]
,

    "Auto Aziendali": [
    "Il veicolo aziendale presenta problemi al motore.",
    "La manutenzione programmata non è stata effettuata.",
    "Occorre l’assegnazione temporanea di un veicolo sostitutivo.",
    "Un’auto ha superato il chilometraggio massimo del leasing.",
    "Il pneumatico anteriore sinistro è usurato oltre i limiti.",
    "È scaduta la polizza assicurativa di un furgone.",
    "Il telepass aziendale non risulta funzionante.",
    "Si richiede installazione di pneumatici invernali.",
    "È stata ricevuta una multa per eccesso di velocità da gestire.",
    "Serve prenotare la revisione obbligatoria.",
    "Un’auto ha subito un danno alla carrozzeria in parcheggio.",
    "Il carburante aziendale non è stato registrato correttamente.",
    "È necessario sostituire la batteria di un veicolo elettrico.",
    "Il veicolo è richiamato in officina per campagna sicurezza.",
    "Si richiede l’autorizzazione per noleggio a breve termine.",
    "Il sensore di pressione gomme segnala valore anomalo.",
    "Il libretto di circolazione non è a bordo del veicolo.",
    "La carta carburante è stata smarrita.",
    "Occorre attivare la pratica di sinistro con l’assicurazione.",
    "È in scadenza il contratto di leasing di due auto.",
    "Il climatizzatore del mezzo non è funzionante.",
    "L'autoradio è stata danneggiata durante l’utilizzo.",
    "La chiave del veicolo è stata persa da un dipendente.",
    "Il navigatore satellitare integrato non si avvia.",
    "Un veicolo ha segnalato anomalie nel sistema ABS.",
    "Richiesta sostituzione veicolo per trasferta urgente.",
    "Il parabrezza presenta una crepa laterale.",
    "L’assicurazione non copre la nuova destinazione d’uso.",
    "Il portabagagli elettronico non si apre correttamente.",
    "Un veicolo aziendale è stato coinvolto in un tamponamento.",
    "Il mezzo aziendale ha manifestato guasti al motore.",
    "La manutenzione periodica prevista non è stata eseguita nei tempi.",
    "È necessaria l’assegnazione provvisoria di un’auto sostitutiva.",
    "Un veicolo ha oltrepassato il limite di chilometri previsto dal leasing.",
    "La gomma anteriore sinistra è eccessivamente consumata e va sostituita.",
    "La copertura assicurativa di un furgone aziendale è scaduta.",
    "Il dispositivo Telepass non risulta attivo o funzionante.",
    "È stata avanzata richiesta per il montaggio di pneumatici invernali.",
    "Ci è stata notificata una sanzione per infrazione di velocità da gestire.",
    "È urgente fissare un appuntamento per la revisione obbligatoria.",
    "L’auto aziendale è stata danneggiata alla carrozzeria mentre era parcheggiata.",
    "Il rifornimento carburante non risulta correttamente registrato nel sistema.",
    "Va cambiata la batteria del veicolo elettrico per malfunzionamento.",
    "Il mezzo è stato convocato in officina per una campagna di richiamo sicurezza.",
    "Serve approvazione per un noleggio auto a breve durata.",
    "Il sistema segnala un’anomalia nella pressione degli pneumatici.",
    "Nel veicolo manca il libretto di circolazione necessario alla guida.",
    "La fuel card aziendale è stata smarrita e va bloccata.",
    "È necessario aprire una pratica assicurativa per danno subito dal veicolo.",
    "Due auto stanno per giungere alla fine del contratto di leasing.",
    "Il climatizzatore del veicolo non eroga aria fredda né calda.",
    "L’impianto audio è stato danneggiato durante l’uso.",
    "Un collaboratore ha perso la chiave dell’autovettura aziendale.",
    "Il navigatore integrato non si accende o non carica la mappa.",
    "Sono stati rilevati malfunzionamenti nel sistema frenante ABS.",
    "Serve con urgenza un veicolo sostitutivo per una trasferta imminente.",
    "È presente una frattura laterale sul parabrezza anteriore.",
    "La copertura assicurativa attuale non include l’utilizzo richiesto.",
    "Il vano bagagli automatico presenta problemi di apertura.",
    "Un veicolo dell’azienda è stato coinvolto in un incidente stradale."
]
,

    "Customer Relation": [
    "Un cliente ha segnalato ritardi nell’assistenza.",
    "È stato ricevuto un reclamo formale.",
    "Un ordine è stato consegnato incompleto.",
    "Una recensione negativa è stata pubblicata su Trustpilot.",
    "Il cliente lamenta addebiti non autorizzati.",
    "È stato richiesto un rimborso per articolo difettoso.",
    "Lo SLA di risposta ticket non è stato rispettato.",
    "Il coupon sconto non è stato applicato al checkout.",
    "Il tracking spedizione non risulta aggiornato.",
    "Un cliente VIP chiede un account manager dedicato.",
    "Una richiesta di reso non è stata processata.",
    "È arrivata una diffida per pubblicità ingannevole.",
    "Il call center ha chiuso la chiamata prima della risoluzione.",
    "Un reclamo social media è diventato virale.",
    "Mancano i punti fedeltà sull’ultima transazione.",
    "La garanzia prodotto non è stata riconosciuta.",
    "Il cliente richiede upgrade di abbonamento senza costi.",
    "È stato segnalato un errore nel configuratore online.",
    "Un ordine ricorrente è stato annullato senza preavviso.",
    "Il cliente chiede prova di consegna firmata.",
    "Il questionario post-vendita non è stato ricevuto.",
    "Un cliente segnala confusione nella politica di reso.",
    "Un cliente chiede l’attivazione immediata del servizio.",
    "La risposta automatica non ha soddisfatto il cliente.",
    "Il canale chat non ha fornito supporto efficace.",
    "È stato contestato il contenuto della mail promozionale.",
    "La gestione del ticket è risultata troppo lenta.",
    "Il cliente segnala un comportamento scorretto in negozio.",
    "La comunicazione sulle condizioni contrattuali è stata giudicata ambigua.",
    "Un cliente attende ancora il callback promesso.",
    "Un cliente ha riportato ritardi nella ricezione dell’assistenza richiesta.",
    "È stato formalizzato un reclamo da parte di un utente.",
    "La merce consegnata risulta incompleta rispetto all’ordine effettuato.",
    "È comparsa una recensione negativa su Trustpilot relativa al nostro servizio.",
    "Un cliente ha segnalato addebiti non autorizzati sul suo conto.",
    "È stata inoltrata richiesta di rimborso per un prodotto difettoso.",
    "Il tempo di risposta previsto per il ticket non è stato rispettato.",
    "Il codice promozionale non è stato riconosciuto in fase di acquisto.",
    "Il tracciamento della spedizione non mostra aggiornamenti recenti.",
    "Un cliente VIP richiede la gestione personalizzata da parte di un account manager.",
    "Una richiesta di restituzione non è ancora stata evasa.",
    "Abbiamo ricevuto una diffida a causa di pubblicità considerata ingannevole.",
    "L’operatore del call center ha interrotto la chiamata prima di risolvere il problema.",
    "Un reclamo pubblicato sui social network ha acquisito visibilità rapidamente.",
    "I punti fedeltà previsti non sono stati accreditati sull’ultima operazione.",
    "La richiesta di attivazione della garanzia è stata rifiutata.",
    "Il cliente desidera passare a un piano superiore senza spese aggiuntive.",
    "È stato riscontrato un malfunzionamento nel configuratore online.",
    "Un ordine con rinnovo automatico è stato annullato senza alcun avviso.",
    "È stata richiesta la prova di consegna con firma del destinatario.",
    "Il sondaggio post-acquisto non è mai stato ricevuto dal cliente.",
    "Il cliente trova poco chiara la nostra politica sui resi.",
    "Una richiesta urgente per l’attivazione del servizio è ancora in sospeso.",
    "Il cliente non è rimasto soddisfatto dalla risposta automatica ricevuta.",
    "La chat online non ha fornito il supporto atteso dall’utente.",
    "Il contenuto dell’email promozionale è stato oggetto di contestazione.",
    "La risoluzione del ticket è stata troppo lenta secondo il cliente.",
    "Ci è stato segnalato un atteggiamento inappropriato da parte del personale di vendita.",
    "Le condizioni contrattuali non sono risultate chiare nella comunicazione al cliente.",
    "Un utente aspetta ancora la richiamata promessa dal supporto clienti."

]
,

    "Risorse Umane": [
    "Alcuni dipendenti segnalano errori nei cedolini.",
    "Ci sono richieste ferie non ancora elaborate.",
    "I dati dei benefit non risultano aggiornati.",
    "Un dipendente chiede il rinnovo del contratto a tempo determinato.",
    "È in scadenza la visita medica periodica di sorveglianza sanitaria.",
    "Mancano le firme sui documenti di onboarding.",
    "Serve pubblicare il calendario ferie aziendale.",
    "Un dipendente richiede smart-working per motivi familiari.",
    "Non è stato registrato lo straordinario di sabato.",
    "Occorre avviare la procedura di maternità.",
    "È richiesta la certificazione formazione sicurezza.",
    "Un badge di accesso è stato disattivato erroneamente.",
    "La valutazione annuale non è stata ancora caricata in HRMS.",
    "Un dipendente segnala mobbing da parte del superiore.",
    "Serve aggiornare la policy GDPR interno personale.",
    "È richiesta l’emissione di certificato di servizio.",
    "Il piano welfare deve essere rinnovato per il prossimo anno.",
    "Un tirocinante ha bisogno di estensione contratto.",
    "Occorre caricare i dati anagrafici nel nuovo gestionale.",
    "Non risulta elaborato il rimborso spese viaggio.",
    "Il badge mensa non risulta attivo per alcuni dipendenti.",
    "Un dipendente richiede la trasformazione del contratto in part-time.",
    "È necessario aggiornare il mansionario del personale tecnico.",
    "Ci sono incongruenze nei giorni di permesso registrati.",
    "Manca la documentazione per il nuovo assunto.",
    "È richiesto un incontro urgente con il rappresentante sindacale.",
    "I moduli di formazione non risultano completati in piattaforma.",
    "Un collaboratore esterno richiede rilascio badge temporaneo.",
    "Serve aggiornare la lista dei contatti di emergenza HR.",
    "Non sono ancora stati pubblicati gli orari per le visite fiscali.",
    "Alcuni dipendenti hanno riscontrato errori nei propri cedolini paga.",
    "Le richieste di ferie inviate non sono ancora state processate.",
    "I dati relativi ai benefit aziendali non risultano aggiornati nel sistema.",
    "Un lavoratore ha chiesto il prolungamento del contratto a tempo determinato.",
    "È in arrivo la scadenza per la visita medica obbligatoria di controllo.",
    "I documenti di inserimento non presentano tutte le firme necessarie.",
    "Va pubblicato il piano ferie aziendale per la prossima stagione.",
    "Un dipendente ha richiesto la modalità di lavoro da remoto per esigenze familiari.",
    "Lo straordinario del turno di sabato non è stato inserito in busta paga.",
    "Bisogna avviare l’iter per il congedo di maternità.",
    "Manca il certificato attestante la formazione obbligatoria in materia di sicurezza.",
    "Un badge di accesso è stato disabilitato per errore.",
    "La scheda di valutazione annuale non è ancora stata caricata nel sistema HRMS.",
    "Un dipendente ha denunciato episodi di mobbing da parte del suo superiore diretto.",
    "Occorre aggiornare le normative GDPR interne relative alla gestione del personale.",
    "È stato richiesto il rilascio del certificato di servizio lavorativo.",
    "Il piano di welfare aziendale va rinnovato in vista del nuovo anno fiscale.",
    "Un tirocinante ha necessità di prolungare la durata del proprio contratto.",
    "I dati anagrafici dei dipendenti devono essere caricati nel nuovo gestionale.",
    "Non risulta effettuato il rimborso per le spese sostenute in viaggio.",
    "Alcuni badge mensa non sono attivi per i dipendenti interessati.",
    "Un dipendente ha chiesto di convertire il contratto a part-time.",
    "È necessario aggiornare le schede mansioni per il personale tecnico.",
    "Sono state riscontrate anomalie nei giorni di permesso registrati.",
    "Manca la documentazione necessaria per completare l’assunzione di un nuovo dipendente.",
    "È richiesto un confronto urgente con il rappresentante dei lavoratori.",
    "Alcuni moduli formativi risultano incompleti sulla piattaforma e-learning.",
    "Un collaboratore esterno ha chiesto l’attivazione temporanea di un badge di accesso.",
    "La lista dei contatti HR da chiamare in emergenza va aggiornata.",
    "Gli orari previsti per le visite fiscali non sono ancora stati resi pubblici."
]
,

    "Acquisti": [
    "La consegna dell’ultimo ordine è in ritardo.",
    "Il fornitore non ha rispettato i termini concordati.",
    "Manca la conferma d’ordine per i materiali richiesti.",
    "Il preventivo ricevuto supera il budget disponibile.",
    "È necessario avviare una gara per la fornitura IT.",
    "Il contratto quadro con il fornitore scade a fine mese.",
    "Il numero di lotto non corrisponde ai documenti di spedizione.",
    "È stata riscontrata merce danneggiata all’arrivo.",
    "Serve variazione degli INCOTERMS per una spedizione estera.",
    "Il prezzo unitario non corrisponde all’offerta sottoscritta.",
    "Il fornitore chiede pagamento anticipato non previsto.",
    "Manca certificazione CE sui componenti consegnati.",
    "Il magazzino segnala rischio stock-out su articolo critico.",
    "Un ordine è stato emesso due volte per errore.",
    "Occorre registrare una non conformità di fornitura.",
    "Il sistema ERP non ha importato gli ordini aperti.",
    "È richiesta la verifica blacklist fornitori internazionali.",
    "Il capitolato tecnico non è allegato al PO.",
    "Serve negoziare termini di pagamento a 60 giorni.",
    "Un reso fornitore è bloccato in dogana.",
    "Il fornitore ha cambiato IBAN senza preavviso.",
    "Un’offerta è stata inviata senza firma autorizzata.",
    "La fattura del fornitore non rispecchia le condizioni d’acquisto.",
    "Non sono stati rispettati i tempi di consegna parziale.",
    "Il packaging non è conforme alle specifiche tecniche.",
    "Il report di qualità evidenzia difformità ricorrenti.",
    "L’ordine è stato processato con codice prodotto errato.",
    "È necessario aggiornare l’albo fornitori per categoria merceologica.",
    "Il fornitore non ha caricato la documentazione richiesta.",
    "I tempi di approvvigionamento dichiarati non sono più attendibili.",
    "L’ultima fornitura è arrivata in ritardo rispetto alla data prevista.",
    "Il fornitore non ha rispettato le condizioni contrattuali pattuite.",
    "La conferma d’ordine per i materiali richiesti non è pervenuta.",
    "Il preventivo ricevuto eccede il limite di spesa autorizzato.",
    "È necessario indire una gara d’appalto per la nuova fornitura IT.",
    "Il contratto quadro in essere con il fornitore è prossimo alla scadenza.",
    "Il numero di lotto indicato non coincide con i dati sulla bolla di consegna.",
    "All’arrivo è stata rilevata merce danneggiata o non conforme.",
    "Occorre aggiornare gli INCOTERMS per una spedizione internazionale.",
    "Il prezzo per unità differisce da quanto concordato in sede d’offerta.",
    "Il fornitore ha richiesto un pagamento anticipato non previsto dal contratto.",
    "I componenti forniti non sono accompagnati da certificazione CE.",
    "Il magazzino ha segnalato rischio di esaurimento per un articolo critico.",
    "È stato emesso per errore un doppio ordine per lo stesso articolo.",
    "Deve essere registrata una non conformità relativa alla fornitura ricevuta.",
    "Il sistema ERP non ha importato correttamente gli ordini ancora aperti.",
    "È necessaria una verifica della blacklist fornitori esteri.",
    "Il documento tecnico non risulta allegato al purchase order.",
    "Bisogna rinegoziare le condizioni di pagamento a 60 giorni netti.",
    "Un reso merce è attualmente fermo in dogana per controlli.",
    "Il fornitore ha modificato l’IBAN senza comunicazione preventiva.",
    "Una proposta commerciale è stata trasmessa senza firma autorizzata.",
    "La fattura ricevuta non rispetta le condizioni economiche concordate.",
    "Non sono stati rispettati i tempi concordati per la consegna parziale.",
    "Il confezionamento non risulta conforme agli standard tecnici richiesti.",
    "Il report qualità ha evidenziato difformità ricorrenti nel prodotto.",
    "L’ordine è stato gestito con un codice articolo errato.",
    "Va aggiornato l’albo fornitori con l’inserimento per categoria merceologica.",
    "Il fornitore non ha caricato la documentazione richiesta sulla piattaforma.",
    "I tempi di fornitura dichiarati non risultano più affidabili."
]
,

    "Servizi": [
    "Il sistema informatico principale non risponde.",
    "Si è verificato un guasto all’impianto.",
    "Il supporto tecnico non ha ancora risposto.",
    "La rete Wi-Fi aziendale è intermittente.",
    "Il condizionatore del data-center non funziona.",
    "Un’interruzione di corrente ha causato downtime.",
    "Il servizio di pulizie ha saltato il turno serale.",
    "Il software ERP segnala errore 500 in produzione.",
    "L’ascensore principale è fuori servizio.",
    "La stampante di rete è bloccata in jam carta.",
    "Il certificato SSL del sito sta per scadere.",
    "Il sistema CCTV non registra dalle 02:00.",
    "È necessario sostituire le lampade nel parcheggio.",
    "Un UPS segnala batteria in fault.",
    "Il ticket di help-desk #982 non è stato aggiornato.",
    "Il generatore di backup non parte in automatico.",
    "L’impianto idraulico ha una perdita nei bagni.",
    "Un firewall blocca traffico SMTP legittimo.",
    "Il servizio cloud ha segnalato degrado prestazioni.",
    "La piattaforma e-mail supera la quota di storage.",
    "L'antispam blocca comunicazioni interne importanti.",
    "Il sistema di badge elettronico non registra gli accessi.",
    "Il portale intranet aziendale è offline da stamattina.",
    "Il servizio di catering ha consegnato con ritardo.",
    "Il climatizzatore delle sale riunioni è fuori uso.",
    "La pulizia dei vetri non è stata effettuata nel piano 4.",
    "Il servizio di gestione rifiuti non ha ritirato i materiali.",
    "Il backup notturno dei dati non è stato completato.",
    "I sensori antincendio segnalano un’anomalia continua.",
    "Il sistema di ticketing è lento e presenta errori casuali.",
    "Il sistema informatico centrale risulta non accessibile.",
    "C'è stato un malfunzionamento a livello impiantistico.",
    "Non è ancora pervenuta una risposta da parte del supporto tecnico.",
    "La connessione Wi-Fi aziendale presenta interruzioni frequenti.",
    "Il climatizzatore del data center non è operativo.",
    "Un blackout elettrico ha causato un’interruzione dei servizi.",
    "Il servizio di pulizia non ha coperto il turno previsto in serata.",
    "Il software gestionale ERP restituisce un errore 500 in ambiente live.",
    "L’ascensore principale è attualmente non funzionante.",
    "La stampante di rete si è inceppata per un blocco della carta.",
    "Il certificato SSL del sito web è in prossimità di scadenza.",
    "Il sistema di videosorveglianza non registra dalle due del mattino.",
    "Vanno sostituite le luci nel parcheggio aziendale per malfunzionamento.",
    "L’UPS segnala un problema alla batteria in modalità fault.",
    "Il ticket help desk numero 982 non risulta aggiornato nel sistema.",
    "Il gruppo elettrogeno di emergenza non si avvia automaticamente.",
    "Una perdita idrica è stata rilevata nei servizi igienici.",
    "Il firewall sta bloccando traffico SMTP considerato legittimo.",
    "Si rileva un calo delle prestazioni sul servizio cloud.",
    "La casella e-mail ha superato il limite di archiviazione disponibile.",
    "Il filtro antispam sta bloccando comunicazioni aziendali interne.",
    "Il sistema badge non sta registrando gli ingressi del personale.",
    "Il portale intranet risulta offline fin dalle prime ore della mattina.",
    "Il catering ha effettuato la consegna con un ritardo non previsto.",
    "L’impianto di climatizzazione nelle sale riunioni è fuori uso.",
    "La vetreria non è stata pulita al quarto piano come programmato.",
    "La raccolta rifiuti aziendale non ha effettuato il ritiro previsto.",
    "Il backup automatico notturno dei file non è stato completato.",
    "I sensori antincendio continuano a segnalare un malfunzionamento.",
    "Il portale ticketing aziendale è lento e mostra errori sporadici."
]

}