# Issue sentences – corpo email (versione estesa)
issues = {
    "Istruzione/formazione/inclusione scolastica": [
        "Mio figlio con disabilità non ha ricevuto il supporto dell'insegnante di sostegno.",
        "La scuola non ha predisposto il Piano Educativo Individualizzato.",
        "Il docente di sostegno è stato assegnato solo a metà anno scolastico.",
        "Il bambino non può accedere all'aula al piano superiore per assenza di ascensore.",
        "La famiglia chiede informazioni sui percorsi di inclusione scolastica disponibili.",
        "Non è stata convocata la riunione del GLHO per la revisione del PEI.",
        "Il ragazzo con DSA non ha ricevuto gli strumenti compensativi previsti.",
        "La scuola non dispone di materiali didattici in formato accessibile.",
        "È stato segnalato un ritardo nell'attivazione del servizio di trasporto scolastico.",
        "L'assistente educativo non è presente durante le ore pomeridiane.",
        "Il PEI non è stato aggiornato dopo la nuova valutazione della commissione medica.",
        "La famiglia lamenta che il figlio viene escluso dalle attività extrascolastiche.",
        "Non è stato attivato il servizio di assistenza specialistica in classe.",
        "Il progetto di orientamento post-scuola non è stato presentato alla famiglia.",
        "La scuola non ha partecipato all'incontro con i servizi sociali.",
        "Il minore non ha accesso ai laboratori informatici per mancanza di postazioni adattate.",
        "È richiesta una valutazione neuropsicologica che la scuola non ha ancora avviato.",
        "Il ragazzo viene spesso allontanato dalla classe senza motivazione valida.",
        "Non è stata comunicata alla famiglia la composizione del gruppo di lavoro inclusivo.",
        "Il piano di studi personalizzato non riflette le reali capacità del bambino.",
        "Sono stati segnalati episodi di esclusione durante le attività di gruppo in classe.",
        "La scuola non ha attivato misure dispensative per l'alunno con dislessia.",
        "Il servizio di integrazione scolastica non è coordinato con i servizi territoriali.",
        "Il bambino non ha ancora ricevuto la diagnosi funzionale aggiornata.",
        "L'insegnante curriculare non collabora con il docente di sostegno.",
        "È richiesto un corso di formazione per i docenti sull'autismo.",
        "Non è stato predisposto il materiale adattato per lo studente ipovedente.",
        "La scuola non ha comunicato le modalità di valutazione personalizzata.",
        "Il passaggio tra ordini scolastici non è stato gestito in continuità.",
        "Il minore con disturbo dello spettro autistico non ha ricevuto la figura dell'assistente.",
        "La famiglia non è stata coinvolta nella stesura del Piano Didattico Personalizzato.",
        "Non sono stati garantiti gli ausili tecnologici previsti nel PEI.",
        "Il bambino è stato inserito in una classe senza il necessario supporto.",
        "Le attività di inclusione non sono state documentate nel fascicolo personale.",
        "È richiesto un incontro urgente con la dirigenza scolastica per discutere l'inclusione.",
        "Il servizio di supporto psicologico non è attivo nella scuola.",
        "Il ragazzo viene escluso dalle gite scolastiche per mancanza di assistenza.",
        "La scuola non ha predisposto un piano di emergenza per alunni con disabilità motorie.",
        "Non è stata attivata la figura dello specialista di comunicazione aumentativa alternativa.",
        "La famiglia chiede chiarimenti sul diritto all'insegnante di sostegno per tutte le ore.",
        "Il percorso formativo post-diploma non è stato pianificato dall'istituto.",
        "Non risulta redatto il verbale dell'ultimo GLHO.",
        "Il bambino riceve meno ore di sostegno rispetto a quanto previsto dalla certificazione.",
        "La scuola non dispone di un piano di accessibilità degli spazi educativi.",
        "Non sono stati coinvolti i genitori nella scelta degli strumenti compensativi.",
        "Il docente di sostegno non ha ricevuto formazione specifica per la disabilità dell'alunno.",
        "Il ragazzo è stato bocciato senza che fosse stata applicata la normativa per i BES.",
        "La scuola non ha risposto alla richiesta di attivazione del PDP nei tempi previsti.",
        "Non sono stati garantiti i tempi aggiuntivi durante le verifiche scritte.",
        "Il minore con disabilità uditiva non ha accesso all'interprete LIS.",
        "La famiglia lamenta la mancata comunicazione sulle assenze del docente di sostegno.",
        "Non è stato predisposto un percorso di tirocinio formativo per lo studente.",
        "Il bambino è l'unico con disabilità nella classe e non riceve supporto adeguato.",
        "Non risulta attivo nessun sportello di ascolto nella scuola frequentata.",
        "La scuola non ha previsto attività di sensibilizzazione sulla disabilità.",
        "Non è stata garantita la continuità dell'insegnante di sostegno nel passaggio di classe.",
        "Il piano personalizzato non viene rispettato nella pratica quotidiana.",
        "Il minore ha difficoltà di apprendimento non ancora certificate dalla scuola.",
        "La famiglia chiede supporto per avviare la procedura di certificazione scolastica.",
        "Non sono stati attivati percorsi di alternanza scuola-lavoro adatti alla disabilità."
    ],

    "Strutture socio-sanitarie": [
        "La struttura residenziale non garantisce personale sufficiente durante la notte.",
        "Il centro diurno non ha posti disponibili per l'inserimento del nostro assistito.",
        "La casa famiglia non è dotata di ausili adeguati per persone non deambulanti.",
        "Il servizio di assistenza nella struttura è stato ridotto senza preavviso.",
        "La struttura non ha rispettato il progetto individuale concordato.",
        "Non vengono svolte attività ricreative nella residenza sanitaria.",
        "L'ospite segnala condizioni igieniche insufficienti nei bagni della struttura.",
        "Non è stato rinnovato il contratto con l'educatore professionale.",
        "La lista d'attesa per il centro diurno supera i 12 mesi.",
        "La struttura residenziale non dispone di uno psicologo dedicato.",
        "L'accesso ai familiari è stato limitato senza motivazione clinica.",
        "Non è stato comunicato il cambio del responsabile del caso.",
        "La struttura non ha adottato il protocollo antiviolenza richiesto.",
        "Il piano di assistenza individuale non è stato aggiornato da oltre un anno.",
        "La struttura ospita persone con profili di bisogno molto diversi senza separazione.",
        "Non vengono organizzati incontri periodici tra famiglie e operatori.",
        "L'orario di apertura del centro diurno non è compatibile con le esigenze lavorative dei caregiver.",
        "La struttura non dispone di un medico di riferimento interno.",
        "Non sono stati attivati percorsi di autonomia per gli ospiti.",
        "Il personale non ha ricevuto formazione specifica per la gestione dell'autismo.",
        "La struttura non garantisce la continuità relazionale con gli educatori.",
        "Il centro semiresidenziale ha sospeso le attività per carenza di personale.",
        "Non è stata effettuata la valutazione multidimensionale aggiornata.",
        "L'ospite ha segnalato comportamenti inappropriati da parte di un operatore.",
        "Non vengono rispettati i tempi dei pasti previsti nel regolamento.",
        "La struttura non dispone di un piano di uscita per le emergenze accessibile.",
        "Il progetto terapeutico riabilitativo non è stato aggiornato.",
        "Non sono garantiti momenti di privacy adeguati per gli ospiti.",
        "La struttura non ha procedure per la gestione delle crisi comportamentali.",
        "L'accesso alla struttura è difficoltoso per i visitatori con disabilità motoria.",
        "Non viene effettuata la verifica periodica del progetto di vita dell'ospite.",
        "La famiglia chiede il trasferimento in una struttura più vicina al domicilio.",
        "Il personale è insufficiente nelle ore di punta della mattina.",
        "Non vengono somministrati i farmaci nelle dosi e nei tempi prescritti.",
        "La struttura non dispone di spazi verdi accessibili per attività all'aperto.",
        "Non è stato attivato il servizio di trasporto per i frequentatori del centro diurno.",
        "La struttura non garantisce l'accesso a un'assistente sociale di riferimento.",
        "Il regolamento interno della struttura non è stato comunicato alla famiglia.",
        "La qualità del pasto non è conforme alle indicazioni del medico.",
        "Non vengono documentate le attività quotidiane svolte dall'ospite.",
        "La struttura ha aumentato le rette senza adeguato preavviso.",
        "Non è disponibile una figura di mediatore familiare nella struttura.",
        "L'ospite non partecipa ad alcuna attività per mancanza di stimolazione.",
        "La struttura non ha comunicato i criteri per la graduatoria di accesso.",
        "Non vengono garantite uscite sul territorio per gli ospiti della RSA.",
        "La struttura non dispone di tecnologie assistive per la comunicazione.",
        "Non è stato redatto il piano di dimissione protetta al termine del ricovero.",
        "La struttura non collabora con il medico di medicina generale dell'ospite.",
        "Non sono previste attività di musicoterapia o arteterapia nella struttura.",
        "L'ospite non può ricevere visite nelle fasce orarie che preferisce."
    ],

    "Rapporti con datori di lavoro": [
        "Il datore di lavoro non ha adattato la postazione di lavoro alla disabilità del dipendente.",
        "Il lavoratore con disabilità è stato trasferito senza il suo consenso.",
        "L'azienda non ha rispettato le quote di riserva previste dalla legge 68/99.",
        "È stato segnalato un licenziamento illegittimo di un lavoratore con disabilità.",
        "Il datore di lavoro si rifiuta di concedere i permessi ex legge 104.",
        "Non viene garantita la flessibilità oraria necessaria per le terapie mediche.",
        "Il lavoratore con disabilità non riceve la stessa formazione degli altri colleghi.",
        "L'azienda non ha comunicato i diritti del lavoratore con certificazione di disabilità.",
        "Il dipendente segnala di essere escluso dalle riunioni aziendali.",
        "Il datore di lavoro ha negato il telelavoro nonostante la certificazione medica.",
        "Non sono stati forniti gli ausili tecnologici richiesti per lo svolgimento del lavoro.",
        "L'azienda non ha applicato le agevolazioni fiscali previste per l'assunzione di disabili.",
        "Il lavoratore è stato declassato senza giustificazione dopo la diagnosi di disabilità.",
        "Non è stato attivato il percorso di reinserimento lavorativo dopo un lungo periodo di malattia.",
        "Il contratto di lavoro non prevede le clausole di tutela per i lavoratori con disabilità.",
        "Il datore di lavoro non ha rispettato le indicazioni del medico competente.",
        "Il lavoratore con disabilità psichica è stato messo in una posizione non adeguata.",
        "Non è stato effettuato il collocamento mirato richiesto dall'ufficio competente.",
        "L'azienda non ha partecipato agli incontri di mediazione convocati dal servizio.",
        "Il datore di lavoro ha rifiutato di applicare la valutazione del rischio per i lavoratori disabili.",
        "Non sono stati rispettati i tempi di risposta alla convocazione dei servizi per l'impiego.",
        "Il lavoratore lamenta condizioni di lavoro discriminatorie rispetto ai colleghi.",
        "L'azienda non ha predisposto un piano di emergenza accessibile per il lavoratore.",
        "Non vengono riconosciuti i diritti di carriera al lavoratore con disabilità.",
        "Il datore di lavoro ha chiesto al dipendente di svolgere mansioni non compatibili con la sua disabilità.",
        "Non è stata rispettata la normativa sul divieto di discriminazione per disabilità.",
        "Il dipendente non è stato informato delle opportunità di formazione continua.",
        "Il datore di lavoro ha rifiutato di attivare convenzioni con i Centri per l'impiego.",
        "Non è stata garantita la sorveglianza sanitaria specifica per il lavoratore.",
        "Il lavoratore chiede supporto per rinegoziare le condizioni contrattuali.",
        "L'azienda ha licenziato il dipendente durante il periodo di malattia.",
        "Non sono state messe a disposizione attrezzature di sicurezza adeguate.",
        "Il responsabile HR non risponde alle richieste del lavoratore con disabilità.",
        "Non è stato attivato il tutoraggio aziendale previsto dalla convenzione.",
        "Il dipendente segnala pressioni affinché si dimetta volontariamente.",
        "Non sono stati riconosciuti i giorni di permesso per accertamenti diagnostici.",
        "L'azienda non ha comunicato i risultati della valutazione dei rischi.",
        "Il lavoratore chiede che venga applicato il piano di accomodamento ragionevole.",
        "Non è stata rispettata la riservatezza dei dati sensibili del dipendente.",
        "Il datore di lavoro non ha risposto alla richiesta di modifica dei turni.",
        "Il lavoratore è stato escluso dai benefici aziendali riservati al personale.",
        "Non è stato predisposto un piano di sicurezza personalizzato per il disabile.",
        "L'azienda non ha rinnovato il contratto a scadenza senza fornire spiegazioni.",
        "Il dipendente segnala di essere ignorato nelle comunicazioni interne.",
        "Non è stato attivato il percorso di accompagnamento al lavoro previsto.",
        "Il datore di lavoro non ha applicato le deduzioni fiscali per i lavoratori con disabilità.",
        "Non è stato rispettato l'orario ridotto concordato con il medico del lavoro.",
        "Il lavoratore non ha ricevuto la valutazione periodica delle performance.",
        "L'azienda non ha adeguato gli spazi comuni alle esigenze del dipendente.",
        "Il contratto non include clausole di protezione per le persone con disabilità cronica."
    ],

    "Accessibilità/barriere architettoniche/mobilità e trasporti/barriere digitali e media": [
        "L'edificio comunale non dispone di rampa di accesso per sedie a rotelle.",
        "Il marciapiede è ostruito da ostacoli che impediscono il transito in sedia a rotelle.",
        "L'ascensore del palazzo pubblico è fuori servizio da settimane.",
        "Non è disponibile un servizio di trasporto adattato nel territorio.",
        "Il portale web del Comune non è accessibile agli utenti non vedenti.",
        "Il semaforo non emette segnale sonoro per i non vedenti.",
        "Il mezzo pubblico non dispone di pedana per la salita in carrozzina.",
        "Il parcheggio riservato ai disabili viene regolarmente occupato da veicoli non autorizzati.",
        "Il sito istituzionale non risponde agli standard WCAG di accessibilità.",
        "Non esiste un percorso tattile per non vedenti nella piazza centrale.",
        "La stazione ferroviaria non dispone di ascensore per i binari.",
        "Il modulo online per la richiesta di servizi non è compatibile con screen reader.",
        "Non è disponibile l'interprete LIS nei servizi pubblici locali.",
        "Il bus di linea non si abbassa con il sistema pneumatico per facilitare la salita.",
        "L'ingresso principale del municipio non ha apertura automatica delle porte.",
        "Non esiste una versione in linguaggio facile dei documenti ufficiali.",
        "Il servizio di trasporto scolastico non è disponibile per alunni con carrozzina.",
        "L'app mobile del Comune non è compatibile con i software di lettura vocale.",
        "Non è presente segnaletica in Braille negli uffici pubblici.",
        "Le strisce pedonali non hanno segnalazione tattile a terra.",
        "Il taxi adattato non copre le fasce orarie notturne.",
        "La programmazione televisiva locale non prevede sottotitoli.",
        "Il sito web dell'ospedale non ha versione ad alto contrasto per ipovedenti.",
        "Non sono disponibili documenti sanitari in formato accessibile.",
        "La fermata del bus non è dotata di pedana rialzata.",
        "Non esiste un servizio di accompagnamento per le persone non autosufficienti.",
        "Il palazzo storico non può essere dotato di ascensore per vincoli architettonici.",
        "Il parcheggio multipiano non ha spazi adeguati per veicoli adattati.",
        "Non è disponibile il Wi-Fi pubblico nelle strutture comunali.",
        "L'ufficio postale non è raggiungibile con sedia a rotelle.",
        "Non esiste un percorso accessibile tra la fermata del bus e l'ospedale.",
        "Il portale per l'autocertificazione non funziona con la tastiera senza mouse.",
        "La biblioteca non dispone di audiolibri aggiornati.",
        "Non è prevista interpretazione LIS nelle conferenze pubbliche.",
        "Il sito del trasporto pubblico non consente la prenotazione assistita.",
        "La rampa di accesso alla stazione è troppo ripida per una carrozzina autonoma.",
        "Non esiste segnaletica in lingua facile negli uffici sanitari.",
        "Il treno regionale non dispone di spazio per la carrozzina nel vagone.",
        "Non è stato rimosso il gradino d'ingresso dell'ufficio anagrafe.",
        "Le comunicazioni istituzionali non prevedono versione audio.",
        "Non è attivo il servizio Deroga ZTL per veicoli adattati.",
        "L'applicazione per i pagamenti digitali non è accessibile tramite screen reader.",
        "Non esiste un piano di abbattimento delle barriere architettoniche nel Comune.",
        "La piattaforma di telemedicina non funziona correttamente con le tecnologie assistive.",
        "Il parco pubblico non ha percorsi pavimentati per carrozzine.",
        "Non è previsto un servizio di interprete a distanza nelle strutture sanitarie.",
        "L'app di prenotazione del trasporto non è disponibile per utenti con disabilità visiva.",
        "Le scale mobili della metropolitana sono spesso fuori servizio.",
        "Non esiste un piano comunale per il trasporto di persone con grave disabilità.",
        "Il sito dell'ASL non consente la prenotazione di visite con sintesi vocale."
    ],

    "Inclusione lavorativa": [
        "Il percorso di tirocinio formativo non è stato avviato nonostante la richiesta.",
        "Non esiste un servizio di orientamento lavorativo per persone con disabilità nel territorio.",
        "Il curriculum vitae del candidato con disabilità non viene preso in considerazione.",
        "Non sono stati attivati i percorsi di borsa lavoro previsti dalla ASL.",
        "Il Centro per l'impiego non ha personale formato per il collocamento mirato.",
        "Il progetto di inserimento lavorativo è stato sospeso senza motivazione.",
        "L'azienda convenzionata non ha rispettato i tempi previsti per l'inserimento.",
        "Non è stata garantita la presenza del tutor durante il periodo di tirocinio.",
        "Il candidato con disabilità è stato scartato senza che venisse applicato il collocamento obbligatorio.",
        "Non vengono organizzati incontri tra persone con disabilità e potenziali datori di lavoro.",
        "Il progetto di work inclusion non include competenze digitali di base.",
        "Non è stato predisposto un piano di accompagnamento personalizzato al lavoro.",
        "La borsa lavoro è stata interrotta prima del completamento del percorso.",
        "Non esistono incentivi per le imprese che assumono persone con disabilità nel territorio.",
        "Il servizio di accompagnamento al lavoro non copre i week-end.",
        "Non è stata effettuata la valutazione delle competenze della persona con disabilità.",
        "L'inserimento in cooperativa sociale non ha previsto un percorso di tutoraggio.",
        "Non sono stati attivati percorsi di formazione professionale adattati.",
        "La persona con disabilità psichica non ha accesso ai programmi di reinserimento.",
        "Non esiste raccordo tra servizi sociali e centri per l'impiego.",
        "Il tirocinio non è stato rinnovato nonostante la valutazione positiva.",
        "Non viene garantita una sede di lavoro accessibile nell'ambito del collocamento.",
        "Il dossier di presentazione al datore di lavoro non include le esigenze specifiche del candidato.",
        "Non è previsto un fondo per coprire i costi degli ausili sul posto di lavoro.",
        "La persona con disabilità visiva non ha accesso ai corsi di informatica necessari.",
        "Non vengono organizzati stage in aziende con esperienze di inclusione consolidate.",
        "Il percorso di autonomia lavorativa non prevede attività di simulazione.",
        "Non è stato attivato il progetto di inclusione lavorativa finanziato dal Comune.",
        "La famiglia non è stata coinvolta nel progetto di inserimento lavorativo.",
        "Non è disponibile un servizio di mediazione tra persona con disabilità e datore di lavoro.",
        "Il percorso lavorativo non è stato personalizzato sulle potenzialità della persona.",
        "Non esistono cooperative sociali di tipo B attive nel territorio.",
        "Non è stato rispettato il piano di inserimento progressivo nelle mansioni.",
        "Il tutoraggio aziendale è stato affidato a una persona non formata.",
        "Non è stato previsto un adattamento degli orari per esigenze terapeutiche.",
        "La convenzione tra azienda e servizi è scaduta senza rinnovo.",
        "Non viene effettuata la verifica periodica del percorso di inserimento.",
        "Il candidato non è stato informato delle agevolazioni previste per le aziende.",
        "Non è stato attivato il servizio di assistenza in loco durante il tirocinio.",
        "Il progetto di orientamento non include la conoscenza dei diritti del lavoratore.",
        "Non esistono sportelli informativi sul collocamento mirato nel territorio.",
        "La persona ha concluso la formazione ma non ha trovato sbocchi lavorativi.",
        "Non sono state attivate convenzioni con aziende private per l'inserimento.",
        "Il percorso di inclusione lavorativa non è stato adeguato alla diagnosi aggiornata.",
        "Non è stata garantita la riservatezza dei dati sanitari durante la selezione.",
        "Non vengono documentati i progressi nel percorso di inclusione.",
        "Il servizio non ha risposto alla richiesta di attivazione del collocamento mirato.",
        "Non è prevista la figura del job coach nel progetto di inserimento.",
        "Il giovane con disabilità intellettiva non ha accesso ai percorsi di apprendistato.",
        "Non è stato attivato nessun percorso di alternanza scuola-lavoro adatto."
    ],

    "Salute/sanità/progetto di vita/assistenza domiciliare": [
        "L'assistenza domiciliare non è stata attivata nei tempi previsti.",
        "Il progetto di vita non è stato redatto nonostante le reiterate richieste.",
        "Il medico di base non è disponibile a domicilio per pazienti non trasportabili.",
        "Non è stato rinnovato il piano terapeutico del farmaco essenziale.",
        "Il servizio ADI è stato ridotto senza coinvolgere la famiglia.",
        "Non è stata effettuata la valutazione UVMD aggiornata.",
        "L'assistente domiciliare non ha ricevuto formazione sulla disabilità specifica.",
        "Il ticket sanitario è stato calcolato in maniera errata.",
        "Non è stato attivato il progetto individuale ai sensi della legge 328/2000.",
        "Il caregiver familiare non riceve supporto né riconoscimento istituzionale.",
        "Non vengono garantite le visite specialistiche in tempi adeguati.",
        "La fornitura di ausili è bloccata da mesi per problemi burocratici.",
        "Il piano di riabilitazione non viene rispettato dagli operatori domiciliari.",
        "La persona non ha accesso a cure dentistiche convenzionate.",
        "Non è stata attivata la continuità assistenziale dopo la dimissione ospedaliera.",
        "Il servizio di fisioterapia domiciliare è stato sospeso.",
        "Non è stata comunicata alla famiglia la variazione degli operatori assegnati.",
        "Il progetto di vita non include obiettivi condivisi con la persona disabile.",
        "Non è stata fornita la carrozzina elettrica prescritta dallo specialista.",
        "Il Comune non ha attivato il fondo per la non autosufficienza.",
        "Non viene garantita la presenza dell'infermiere nelle ore notturne.",
        "La persona con disabilità grave non può accedere ai centri di riabilitazione.",
        "Non è stato redatto il Piano Assistenziale Individualizzato aggiornato.",
        "L'ASL non ha risposto alla richiesta di valutazione per invalidità civile.",
        "Il servizio di assistenza personale è stato interrotto durante le festività.",
        "Non è previsto supporto psicologico per i familiari del disabile.",
        "La persona non riesce ad accedere al pronto soccorso per mancanza di trasporto.",
        "Non vengono attivate le misure di supporto per il caregiver in caso di emergenza.",
        "Il progetto riabilitativo non viene aggiornato con le evoluzioni della disabilità.",
        "Non è stata garantita la somministrazione dei farmaci durante le attività diurne.",
        "La domanda per l'assegno di cura non ha ricevuto risposta.",
        "Non è disponibile un medico specialista per la disabilità rara nel territorio.",
        "Il progetto di vita è stato redatto senza il coinvolgimento diretto della persona.",
        "Non è stata attivata l'assistenza protesica prevista dalla prescrizione.",
        "I tempi di attesa per la valutazione della commissione medica sono eccessivi.",
        "Non vengono effettuati controlli periodici sulla qualità dell'assistenza domiciliare.",
        "Non è stata rispettata la scelta della persona riguardo al proprio progetto di vita.",
        "Il servizio di sollievo per il caregiver non è disponibile nel territorio.",
        "La persona disabile non può accedere a farmaci sperimentali disponibili altrove.",
        "Non è stata garantita la coerenza tra il progetto di vita e l'assistenza domiciliare.",
        "La domanda di accesso all'UVM non è stata ancora processata.",
        "Non sono stati forniti ausili per la comunicazione aumentativa alternativa.",
        "Il piano di dimissione dall'ospedale non include un progetto di assistenza domiciliare.",
        "Non è disponibile un servizio di respiro per il caregiver.",
        "Il medico di base non collabora con i servizi specialistici per il disabile.",
        "Non è stata attivata la misura di assistenza residenziale temporanea.",
        "La persona non riceve supporto nutrizionale specifico a domicilio.",
        "Non è stato pianificato il percorso di uscita dalla struttura verso la vita autonoma.",
        "Il progetto individuale non è stato condiviso con tutti gli enti coinvolti.",
        "L'assistente domiciliare non rispetta il progetto di autonomia della persona."
    ],

    "Vita sociale/eventi/sport": [
        "La persona con disabilità non riesce a partecipare agli eventi culturali locali.",
        "Il teatro comunale non ha posti accessibili alle carrozzine.",
        "Non sono previsti eventi inclusivi nel programma estivo del Comune.",
        "La persona con disabilità viene esclusa dalle attività del gruppo parrocchiale.",
        "Non esiste un servizio di accompagnamento per la partecipazione ad eventi sociali.",
        "Il cinema non dispone di cuffie per ipoudenti durante le proiezioni.",
        "Non vengono organizzate uscite sociali per persone con disabilità intellettiva.",
        "L'associazione culturale non prevede attività adatte a persone con disabilità cognitive.",
        "Non esistono eventi sociali accessibili nelle ore serali.",
        "La persona è socialmente isolata per mancanza di opportunità di incontro.",
        "Non è disponibile un servizio di trasporto per la partecipazione ad eventi.",
        "Il festival locale non ha predisposto un piano di accessibilità.",
        "Non sono previsti volontari di supporto durante gli eventi pubblici.",
        "La biblioteca non organizza attività di lettura accessibili.",
        "Il gruppo di auto-aiuto non è accessibile alle persone non deambulanti.",
        "Non esistono spazi di aggregazione per giovani con disabilità nel quartiere.",
        "La persona con disabilità sensoriale non viene coinvolta nelle attività del centro anziani.",
        "Non viene garantito il diritto alla socialità per chi vive in struttura residenziale.",
        "Non sono previsti eventi di sensibilizzazione sulla disabilità rivolti alla cittadinanza.",
        "La persona non riesce a mantenere relazioni sociali per mancanza di supporto.",
        "Non esistono gruppi di volontariato attivi nel supporto alla vita sociale dei disabili.",
        "Gli eventi del Comune non vengono comunicati in formato accessibile.",
        "La persona con disabilità intellettiva non può partecipare al corso di cucina.",
        "Non sono previste attività di tempo libero per persone con autismo.",
        "Il centro di aggregazione giovanile non è accessibile in sedia a rotelle.",
        "Non è stato attivato nessun progetto di vita indipendente per il giovane adulto.",
        "Non esiste un piano di inclusione sociale nel piano di zona.",
        "La persona non può accedere ai luoghi di culto per barriere architettoniche.",
        "Non vengono organizzati campi estivi inclusivi per bambini con disabilità.",
        "Non esiste supporto per la gestione delle relazioni affettive della persona.",
        "La persona con disabilità acquisita ha difficoltà a reinserirsi nel contesto sociale.",
        "Non vengono attivati percorsi di animazione territoriale inclusiva.",
        "Non è garantito l'accompagnamento per la partecipazione a eventi religiosi.",
        "Il quartiere non dispone di spazi verdi accessibili per il tempo libero.",
        "Non è prevista la figura del facilitatore per l'inclusione sociale.",
        "La persona è stata esclusa dalla gita organizzata dall'associazione.",
        "Non esistono percorsi di turismo accessibile nel territorio.",
        "Non vengono organizzate attività di teatro sociale inclusive.",
        "Non è disponibile un servizio di peer support tra persone con disabilità.",
        "L'oratorio non ha previsto attività estive per bambini con disabilità grave.",
        "La persona con disabilità sensoriale non può accedere ai contenuti multimediali degli eventi.",
        "Non viene garantita la partecipazione alle decisioni della comunità locale.",
        "Non esistono spazi di coworking accessibili per persone con disabilità.",
        "Il progetto di vita indipendente non include attività di vita sociale.",
        "Non è previsto nessun laboratorio artistico per persone con disabilità psichica.",
        "La persona non può partecipare alla vita di quartiere per mancanza di trasporto.",
        "Non vengono organizzati eventi di sensibilizzazione nelle scuole.",
        "Non è disponibile supporto per la gestione del tempo libero in autonomia.",
        "La persona con disabilità grave non ha accesso a luoghi di svago.",
        "Non esiste un progetto di supporto alla vita affettiva e sessuale per persone con disabilità."
    ],

    "Altro": [
        "La richiesta non rientra nelle categorie standard disponibili.",
        "Il problema segnalato richiede una valutazione multidisciplinare.",
        "Non è chiaro a quale servizio rivolgersi per questa problematica.",
        "La situazione è complessa e coinvolge più ambiti di intervento.",
        "La persona chiede informazioni generali sui propri diritti.",
        "Non è stato ricevuto nessun riscontro dopo la segnalazione precedente.",
        "La richiesta riguarda un caso non previsto dalla normativa attuale.",
        "Il servizio competente non è stato individuato dall'utente.",
        "La situazione è urgente ma non rientra nelle categorie consuete.",
        "La persona ha bisogno di orientamento generale sui servizi disponibili.",
        "La segnalazione riguarda un problema emerso di recente.",
        "Non si conosce l'ente competente per gestire questa problematica.",
        "La richiesta è di natura informativa e non richiede intervento immediato.",
        "La persona chiede supporto per compilare la documentazione necessaria.",
        "Non è stata identificata la categoria di appartenenza del problema.",
        "La situazione è nuova e non prevista dal sistema di segnalazione.",
        "È necessaria una consulenza generica prima di attivare un servizio specifico.",
        "La persona ha ricevuto informazioni contrastanti da enti diversi.",
        "Il problema non rientra nella competenza di un singolo servizio.",
        "La segnalazione richiede un approfondimento prima dell'inserimento in categoria.",
        "Non è stato possibile determinare l'ambito di competenza corretto.",
        "La persona chiede un incontro conoscitivo senza una richiesta specifica.",
        "La situazione richiede un coordinamento tra servizi che non è ancora avvenuto.",
        "La richiesta non ha trovato risposta adeguata nei servizi esistenti.",
        "La persona non è riuscita ad accedere ai servizi per motivi burocratici.",
        "Non è stata trovata una soluzione nei canali ordinari.",
        "La segnalazione riguarda un disservizio non categorizzabile facilmente.",
        "La persona chiede assistenza per formulare correttamente la propria richiesta.",
        "Non è presente nel territorio un servizio adeguato al bisogno espresso.",
        "La richiesta è stata inviata al servizio sbagliato per errore.",
        "La situazione richiede un intervento straordinario non previsto dalla normativa.",
        "Non esiste un protocollo specifico per la gestione di questo tipo di caso.",
        "La persona chiede supporto per orientarsi tra i servizi disponibili.",
        "La segnalazione è stata fatta anche ad altri enti senza risposta.",
        "Il bisogno espresso non è riconducibile a una categoria esistente.",
        "La persona ha difficoltà a descrivere il problema in modo preciso.",
        "La richiesta è in fase di valutazione preliminare.",
        "Non è stato ancora attivato nessun intervento.",
        "La problematica richiede una risposta multisettoriale.",
        "La persona non ha fiducia nei servizi a causa di esperienze negative passate.",
        "La richiesta è stata ricevuta ma non ancora assegnata al servizio competente.",
        "Non è presente documentazione a supporto della segnalazione.",
        "La persona chiede aggiornamenti su una richiesta già inoltrata.",
        "Non è stata ricevuta alcuna comunicazione dopo l'invio della segnalazione.",
        "La situazione richiede un intervento urgente ma non è stata ancora classificata.",
        "Il problema è noto ma non è stato ancora trovato un ente competente.",
        "La persona è in lista d'attesa per un servizio non categorizzato.",
        "Non è chiaro se il problema rientri nella competenza comunale o regionale.",
        "La richiesta richiede ulteriori informazioni per essere processata.",
        "La persona ha bisogno di supporto per accedere ai servizi digitali."
    ]
}
